os: linux
language: go
go:
- 1.13.5
env:
- GO111MODULE=on
python:
- '3.9'
addons:
  apt:
    packages:
    - build-essential
    - squashfs-tools
    - uuid-dev
    - libuuid1
    - libffi-dev
    - libssl-dev
    - libssl1.0.0
    - libarchive-dev
    - libgpgme11-dev
    - libseccomp-dev
    - wget
    - pkg-config
  homebrew:
    packages:
    - squashfs
    update: true
sudo: required
matrix:
  include:
  - python: '2.6'
  - python: '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_cbafb80fce45_key -iv $encrypted_cbafb80fce45_iv
  -in client_secret_825018774845-ldb1aj6f54s02iu06dncu5r37hgsefme.apps.googleusercontent.com.json.enc
  -out /credentials.json
  -d
- SREGISTRY_GOOGLE_DRIVE_CREDENTIALS=/credentials.json
- sudo chmod u+x .travis/*.sh
- "/bin/bash .travis/setup.sh"
install:
- 
script:
- "/bin/bash .travis/build.sh Singularity"
- "/bin/bash .travis/build.sh -u collection/container --cli google-drive Singularity"
