os: linux
language: go
go:
- 1.13.5
env:
  - GO111MODULE=on SREGISTRY_GOOGLE_DRIVE_CREDENTIALS=/usr/share/credentials.json
python:
- '3.9'
addons:
  apt:
    packages:
    - build-essential
    - squashfs-tools
    - uuid-dev
    - libuuid1
    - libffi-dev
    - libssl-dev
    - libssl1.0.0
    - libarchive-dev
    - libgpgme11-dev
    - libseccomp-dev
    - wget
    - pkg-config
  homebrew:
    packages:
    - squashfs
    update: true
sudo: required
matrix:
  include:
  - python: '2.6'
  - python: '3.5'
before_install:
- sudo openssl aes-256-cbc -K $encrypted_351e9aa214ac_key -iv $encrypted_351e9aa214ac_iv
  -in client_secret_825018774845-0ueebbdcais1jlejbbsv4tt7jngqfk9j.apps.googleusercontent.com.json.enc
  -out /usr/share/credentials.json
  -d
- sudo chmod u+x .travis/*.sh
- "/bin/bash .travis/setup.sh"
install:
- 
script:
- "/bin/bash .travis/build.sh Singularity"
- "/bin/bash .travis/build.sh -u collection/container --cli google-drive Singularity"
