os: linux
language: go
go:
- 1.13.5
env:
  matrix:
  - GO111MODULE=on SREGISTRY_CLIENT=dropbox
  global:
  - secure: QeWV0mYxm0qMIs/BWG6ItkigINJfrzX3KzQjQLtRxKu1C4Mg7yqHcOHmluengrHCRzBolN8Liu47hBvrTGxTw0Vbpomq9WGUqq/RZcc1yCNze7qFA+EPQQU9HxBCqQDlsr5fXBqi/9lClhl301X+8QNmwLdDxuszye4mxMg2XcY8LyXbQbVoxQKzR75yYkNJpgUrzvwg6kVT7oN8mSFCUkeUaNWq9upcEb56HqtN3jZy2RzztelQbaaFcWf/zT+lX/k22rUZZP/3OHVv6ndjQOutKok6xpZstNTNv0cer9i0So5ktSZU2Chp4Bs+rD7Qm6AXTeo2MIQjJKUHqS2bLM/LEspg+B+clyMiwYDdqSx20aNjkgUEIW+BZOM0DOjjnA7KxSTGYr1sYr6tj919eD9fFjucWcn0ivx2IIc95QDS0mB6P0CzVbgIebQ2mbhy/Uk0WvuNbw1vn+NHhCkhtQ+JE9A4zn3PEh6NJmJk5SLCSNj8AgbOUvwphEuLFkM8SNvlBnbZC9yMQIPT4LJwTAXcvEsI2B0wS95ZZ8weGPoel7BGpa2nu9eKFb86u/HMMAJno+Xp/DQwNZvxQ2ohCA5qHlkYsDLA6ChzR7o5uGjg1FhQ6mPzpxxykEbYuRvzZSpBLcvm/6rLYqVQH+aRi/AJPHrWfrX4cyY3V3hWb1E=
python:
- '3.9'
addons:
  apt:
    packages:
    - build-essential
    - squashfs-tools
    - uuid-dev
    - libuuid1
    - libffi-dev
    - libssl-dev
    - libssl1.0.0
    - libarchive-dev
    - libgpgme11-dev
    - libseccomp-dev
    - wget
    - pkg-config
  homebrew:
    packages:
    - squashfs
    update: true
sudo: required
matrix:
  include:
  - python: '2.6'
  - python: '3.5'
before_install:
- sudo chmod u+x .travis/*.sh
- "/bin/bash .travis/setup.sh"
install:
- 
script:
- "/bin/bash .travis/build.sh Singularity"
- "/bin/bash .travis/build.sh -u collection/container --cli dropbox Singularity"
